apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - forecastleApp.yaml
  - rbac.yaml
  # - route.yaml
  - service.yaml
