apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: forecastle-config
  namespace: flux-system
spec:
  chart:
    spec:
      chart: templater
      sourceRef:
        kind: HelmRepository
        name: getupcloud
      version: "1.2.1"
  dependsOn:
    - name: forecastle
  releaseName: forecastle-config
  install:
    createNamespace: false
    disableWait: false
    remediation:
      retries: -1
  upgrade:
    disableWait: false
    remediation:
      retries: -1
  interval: 5m
  targetNamespace: forecastle
  storageNamespace: forecastle
  values:
    templates:
      - apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: forecastle
          namespace: forecastle
        spec:
          ingressClassName: nginx
          rules:
            - host: forecastle.127-0-0-1.nip.io
              http:
                paths:
                  - backend:
                      service:
                        name: forecastle
                        port:
                          number: 80
                    path: /
                    pathType: Prefix
      - apiVersion: forecastle.stakater.com/v1alpha1
        kind: ForecastleApp
        metadata:
          name: grafana
          namespace: forecastle
        spec:
          name: Grafana
          group: monitoring
          icon: https://github.com/stakater/ForecastleIcons/raw/master/grafana.png
          url: http://grafana.127-0-0-1.nip.io
          networkRestricted: false
      - apiVersion: forecastle.stakater.com/v1alpha1
        kind: ForecastleApp
        metadata:
          name: alertmanager
          namespace: forecastle
        spec:
          name: Alertmanager
          group: monitoring
          icon: https://github.com/stakater/ForecastleIcons/raw/master/alert-manager.png
          url: http://alertmanager.127-0-0-1.nip.io
          networkRestricted: false
      - apiVersion: forecastle.stakater.com/v1alpha1
        kind: ForecastleApp
        metadata:
          name: prometheus
          namespace: forecastle
        spec:
          name: Prometheus
          group: monitoring
          icon: https://github.com/stakater/ForecastleIcons/raw/master/prometheus.png
          url: http://prometheus.127-0-0-1.nip.io
          networkRestricted: false
