apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: forecastle
  namespace: flux-system
spec:
  chart:
    spec:
      chart: forecastle
      sourceRef:
        kind: HelmRepository
        name: stakater
      version: "1.0.143"
  dependsOn: []
  #- name: <dependency release>
  releaseName: forecastle
  install:
    createNamespace: true
    disableWait: false
    remediation:
      retries: -1
  upgrade:
    disableWait: false
    remediation:
      retries: -1
  interval: 5m
  targetNamespace: forecastle
  storageNamespace: forecastle
  values:
    forecastle:
      deployment:
        tolerations:
          - key: dedicated
            value: infra
            effect: NoSchedule
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: role
                        operator: In
                        values:
                          - infra
                  topologyKey: topology.kubernetes.io/zone
      config:
        namespaceSelector:
          any: true
          matchNames: []
        crdEnabled: true
      ingress:
        enabled: true
        className: nginx
        hosts:
          - host: forecastle.127-0-0-1.nip.io
            paths:
              - path: /
                pathType: Prefix
